set_location_assignment PIN_M23 -to RESET
set_location_assignment PIN_Y2 -to CLK50MHZ
set_location_assignment PIN_AD11 -to FL_ADDR[22]
set_location_assignment PIN_AD10 -to FL_ADDR[21]
set_location_assignment PIN_AE10 -to FL_ADDR[20]
set_location_assignment PIN_AD12 -to FL_ADDR[19]
set_location_assignment PIN_AC12 -to FL_ADDR[18]
set_location_assignment PIN_AH12 -to FL_ADDR[17]
set_location_assignment PIN_AA8 -to FL_ADDR[16]
set_location_assignment PIN_Y10 -to FL_ADDR[15]
set_location_assignment PIN_AC8 -to FL_ADDR[14]
set_location_assignment PIN_AD8 -to FL_ADDR[13]
set_location_assignment PIN_AA10 -to FL_ADDR[12]
set_location_assignment PIN_AF9 -to FL_ADDR[11]
set_location_assignment PIN_AE9 -to FL_ADDR[10]
set_location_assignment PIN_AB10 -to FL_ADDR[9]
set_location_assignment PIN_AB12 -to FL_ADDR[8]
set_location_assignment PIN_AB13 -to FL_ADDR[7]
set_location_assignment PIN_AA12 -to FL_ADDR[6]
set_location_assignment PIN_AA13 -to FL_ADDR[5]
set_location_assignment PIN_Y12 -to FL_ADDR[4]
set_location_assignment PIN_Y14 -to FL_ADDR[3]
set_location_assignment PIN_Y13 -to FL_ADDR[2]
set_location_assignment PIN_AH7 -to FL_ADDR[1]
set_location_assignment PIN_AG12 -to FL_ADDR[0]
set_location_assignment PIN_AG7 -to FL_CE_N
set_location_assignment PIN_AF12 -to FL_DQ[7]
set_location_assignment PIN_AH11 -to FL_DQ[6]
set_location_assignment PIN_AG11 -to FL_DQ[5]
set_location_assignment PIN_AF11 -to FL_DQ[4]
set_location_assignment PIN_AH10 -to FL_DQ[3]
set_location_assignment PIN_AG10 -to FL_DQ[2]
set_location_assignment PIN_AF10 -to FL_DQ[1]
set_location_assignment PIN_AH8 -to FL_DQ[0]
set_location_assignment PIN_AG8 -to FL_OE_N
set_location_assignment PIN_AE11 -to FL_RST_N
set_location_assignment PIN_Y1 -to FL_RY
set_location_assignment PIN_AC10 -to FL_WE_N
set_location_assignment PIN_AE12 -to FL_WP_N
